name: CI
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
    inputs:
      luxdRepo:
        description: 'lux node github repository'
        required: true
        default: 'luxfi/node'
      luxdBranch:
        description: 'lux branch'
        required: true
        default: 'master'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: check out ${{ github.event.inputs.luxdRepo }} ${{ github.event.inputs.luxdBranch }}
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.inputs.luxdRepo }}
          ref: ${{ github.event.inputs.luxdBranch }}
          path: luxd
          token: ${{ secrets.LUX_PAT }}
      - uses: actions/setup-go@v3
        with:
          go-version: '~1.20.10'
          check-latest: true
      - name: change luxd dep
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          go mod edit -replace github.com/luxfi/node=./node
          go mod tidy
          go clean -modcache # avoid conflicts with the golangci-lint-action cache
      - run: ./scripts/lint_allowed_geth_imports.sh
        shell: bash
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
          working-directory: .
          args: --timeout 3m
  test:
    name: Golang Unit Tests v${{ matrix.go }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11.0, ubuntu-20.04, windows-latest]
    steps:
    - uses: actions/checkout@v3
    - name: check out ${{ github.event.inputs.luxdRepo }} ${{ github.event.inputs.luxdBranch }}
      if: ${{ github.event_name == 'workflow_dispatch' }}
      uses: actions/checkout@v3
      with:
        repository: ${{ github.event.inputs.luxdRepo }}
        ref: ${{ github.event.inputs.luxdBranch }}
        path: luxd
        token: ${{ secrets.LUX_PAT }}
    - uses: actions/setup-go@v3
      with:
        go-version: '~1.20.10'
        check-latest: true
    - name: change luxd dep
      if: ${{ github.event_name == 'workflow_dispatch' }}
      run: |
        go mod edit -replace github.com/luxfi/node=./node
        go mod tidy
    - run: go mod download
      shell: bash
    - run: ./scripts/build.sh evm
      shell: bash
    - run: ./scripts/build_test.sh
      shell: bash
    - run: ./scripts/coverage.sh
      shell: bash
  test-race:
    name: Golang Unit Tests Race Detection v${{ matrix.go }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
    steps:
    - uses: actions/checkout@v3
    - name: check out ${{ github.event.inputs.luxdRepo }} ${{ github.event.inputs.luxdBranch }}
      if: ${{ github.event_name == 'workflow_dispatch' }}
      uses: actions/checkout@v3
      with:
        repository: ${{ github.event.inputs.luxdRepo }}
        ref: ${{ github.event.inputs.luxdBranch }}
        path: luxd
        token: ${{ secrets.LUX_PAT }}
    - uses: actions/setup-go@v3
      with:
        go-version: '~1.20.10'
        check-latest: true
    - name: change luxd dep
      if: ${{ github.event_name == 'workflow_dispatch' }}
      run: |
        go mod edit -replace github.com/luxfi/node=./node
        go mod tidy
    - run: go mod download
      shell: bash
    - run: ./scripts/build.sh evm
      shell: bash
    - run: ./scripts/build_test.sh -race
      shell: bash
  luxd_e2e:
    name: luxd E2E Tests v${{ matrix.go }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]
    steps:
    - uses: actions/checkout@v3
    - name: check out ${{ github.event.inputs.luxdRepo }} ${{ github.event.inputs.luxdBranch }}
      if: ${{ github.event_name == 'workflow_dispatch' }}
      uses: actions/checkout@v3
      with:
        repository: ${{ github.event.inputs.luxdRepo }}
        ref: ${{ github.event.inputs.luxdBranch }}
        path: luxd
        token: ${{ secrets.LUX_PAT }}
    - uses: actions/setup-go@v3
      with:
        go-version: '~1.20.10'
        check-latest: true
    - name: Run e2e tests
      run: E2E_SERIAL=1 ./scripts/tests.e2e.sh
      shell: bash
    - name: Upload testnet network dir
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: testnet-data
        path: ~/.testnetctl/networks/1000
